### ISSUE TITLE
new named graphs created from uploaded trig files

### ISSUE THREAD

**Issue by rashidsabbir** [tetherless-world/whyis#23]
When a trig file is uploaded using python manage.py load, new nanopublications are created by satoru that the triples in the trig file are assigned to. The original named graphs specified in the trig file are lost.

**Comment by jimmccusker** [comment]
This should probably be a different kind of UI than what we are currently doing. The Trig file should probably be posted directly, and assume that each non-nanopub-wrapped graph will become a new  assertion graph.

**Comment by jimmccusker** [comment]
Is this a facet of #18? If so, please close the other one.

**Comment by jimmccusker** [comment]
Named graph URIs are now preserved, and instead of rewriting them, are "wrapped" in nanopublications to record provenance.
