### ISSUE TITLE
improve whyis installation instructions

### ISSUE THREAD

**Issue by marcellobax** [tetherless-world/whyis#33]
Here is one suggestion that I think will improve whyis installation instructions in page: https://tetherless-world.github.io/whyis/install

In *Section* “Add a User” you should append, to the end of the first paragraph, this sentence:
```Go back to whyis user, then go to /apps/whyis and run the following command:```

Note that in the step just before “Add a User”, the user went to privileged root to restart apache and celeryd. Then, when running manage.py (to create a whyis user) with root it won’t work. It gets then a bit confusing at this point.

**Comment by jimmccusker** [comment]
Fixed.
