### ISSUE TITLE
Please cite the DrugBank paper in any future publications

### ISSUE THREAD

**Issue by cknoxrun** [tetherless-world/whyis#43]
Hello, I noticed your paper through a google alert I have on DrugBank. If you could please cite the DrugBank paper in any publications that would be much appreciated.

> Wishart DS, Feunang YD, Guo AC, Lo EJ, Marcu A, Grant JR, Sajed T, Johnson D, Li C, Sayeeda Z, Assempour N, Iynkkaran I, Liu Y, Maciejewski A, Gale N, Wilson A, Chin L, Cummings R, Le D, Pon A, Knox C, Wilson M. DrugBank 5.0: a major update to the DrugBank database for 2018. Nucleic Acids Res. 2017 Nov 8. doi: 10.1093/nar/gkx1037.

Really cool project by the way 👍

**Comment by jimmccusker** [comment]
We had a page limitation, and had to footnote database resources here. I promise when there's room we will cite it properly. We've got another one coming up that will be a big reward for all the provenance you've been tracking.
