### ISSUE TITLE
puppetlabs-stdlib version 6.0.0 breaks elastic-elastic_stack and elastic-elasticsearch install

### ISSUE THREAD

**Issue by nfusionz** [tetherless-world/whyis#49]
On May 22, 2019, version 6.0.0 of [puppetlabs-stdlib](https://forge.puppet.com/puppetlabs/stdlib) was released. The install.sh script seems to pull the latest version, but [elasticsearch](https://forge.puppet.com/elastic/elasticsearch/dependencies) and [elastic_stack](https://forge.puppet.com/elastic/elastic_stack/dependencies) only support puppetlabs-stdlib versions < 6.0.0.

On running install.sh, this seems to cause an error when installing the elasticsearch and elastic_stack modules.

I was able to work around this error by adding `--version <6.0.0` to installation command for puppetlabs-stdlib, but I'm not sure if I should directly push this change to this repository.

On another note, the echo messages are a bit outdated, saying that they are installing version 4.14.0.

**Comment by hansidm** [comment]
In addition, I only made it work with `--version 4.25.1`. I think it should probably work with any `4.x`.

**Comment by nfusionz** [comment]
fdb2fcd5e0bbaeec809ca11aabea6d7df8415f1c and eeae41226890a09e120a842d46d480cfb12c83bf should probably fix the issue.
